# Generated by Django 5.2.7 on 2025-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_address',
            field=models.CharField(blank=True, help_text='Địa chỉ giao hàng mặc định (customer)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_address',
            field=models.CharField(blank=True, help_text='Địa chỉ cửa hàng/quán (merchant)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, help_text='Tên cửa hàng/quán (merchant)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicle_plate',
            field=models.CharField(blank=True, help_text='Biển số xe (shipper)', max_length=32, null=True),
        ),
    ]
