# Generated by Django 5.2.7 on 2025-11-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0003_alter_menuitem_options_alter_merchant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('PICKED_UP', 'Picked up'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PENDING', help_text='Trạng thái xử lý đơn hàng', max_length=32)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', help_text='Trạng thái thanh toán', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền khi checkout', max_digits=12)),
                ('delivery_address', models.CharField(blank=True, default='', help_text='Địa chỉ giao hàng (điền bởi customer)', max_length=255)),
                ('note', models.TextField(blank=True, default='', help_text='Ghi chú thêm của khách (ví dụ: ít cay)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm khách tạo đơn')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm trạng thái đơn được cập nhật lần cuối')),
                ('customer', models.ForeignKey(help_text='Người đặt đơn (role=customer)', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(help_text='Cửa hàng nhận đơn', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='menus.merchant')),
                ('shipper', models.ForeignKey(blank=True, help_text='Shipper đảm nhận đơn này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('ORDER_ISSUE', 'Vấn đề về đơn hàng'), ('FOOD_QUALITY', 'Chất lượng món ăn'), ('DELIVERY_ISSUE', 'Vấn đề giao hàng'), ('PAYMENT_ISSUE', 'Vấn đề thanh toán'), ('OTHER', 'Khác')], default='OTHER', max_length=32)),
                ('title', models.CharField(help_text='Tiêu đề khiếu nại', max_length=255)),
                ('description', models.TextField(help_text='Mô tả chi tiết khiếu nại')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('IN_PROGRESS', 'Đang xử lý'), ('RESOLVED', 'Đã giải quyết'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=32)),
                ('response', models.TextField(blank=True, default='', help_text='Phản hồi từ merchant/admin')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Thời điểm giải quyết', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Khách hàng gửi khiếu nại', on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, help_text='Người xử lý khiếu nại', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_handled', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Đơn hàng liên quan', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(help_text='Tên món tại thời điểm đặt', max_length=200)),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Giá đơn vị tại thời điểm đặt', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Số lượng món khách chọn')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='price_snapshot * quantity', max_digits=12)),
                ('menu_item', models.ForeignKey(blank=True, help_text='Tham chiếu món gốc (có thể null nếu món bị xóa sau này)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menus.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_rating', models.PositiveIntegerField(default=5, help_text='Đánh giá đơn hàng (1-5 sao)')),
                ('merchant_rating', models.PositiveIntegerField(blank=True, help_text='Đánh giá cửa hàng (1-5 sao)', null=True)),
                ('shipper_rating', models.PositiveIntegerField(blank=True, help_text='Đánh giá shipper (1-5 sao)', null=True)),
                ('comment', models.TextField(blank=True, default='', help_text='Nhận xét của khách hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Khách hàng đánh giá', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Đơn hàng được đánh giá', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Đánh giá món (1-5 sao)')),
                ('comment', models.TextField(blank=True, default='', help_text='Nhận xét về món')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.orderitem')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to='orders.review')),
            ],
            options={
                'unique_together': {('review', 'order_item')},
            },
        ),
    ]
