# Generated by Django 5.2.7 on 2025-10-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('merchant_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên hiển thị của cửa hàng/quán ăn', max_length=120)),
                ('address', models.CharField(blank=True, help_text='Địa chỉ quán / bếp (có thể bỏ trống)', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại liên hệ cửa hàng', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Cửa hàng có đang hoạt động nhận đơn hay tạm đóng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Chủ sở hữu chính của cửa hàng này', on_delete=django.db.models.deletion.CASCADE, related_name='owned_merchants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', help_text='Vai trò trong merchant', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(help_text='Merchant mà user tham gia', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='menus.merchant')),
                ('user', models.ForeignKey(help_text='User thuộc merchant này', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'merchant')},
            },
        ),
    ]
